# Generated by Django 5.1.1 on 2024-09-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=150)),
                ('idade', models.IntegerField()),
                ('genero', models.CharField(max_length=10)),
                ('alergias', models.TextField(blank=True)),
                ('doencas_preexistentes', models.TextField(blank=True)),
                ('medicamentos_atual', models.TextField(blank=True)),
                ('cirugias', models.TextField(blank=True)),
            ],
        ),
    ]
