# Generated by Django 5.1.1 on 2024-11-10 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostosBairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True, null=True)),
                ('posto_horario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='saude.endereco')),
            ],
        ),
        migrations.AddField(
            model_name='endereco',
            name='posto_bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saude.postosbairro'),
        ),
    ]
