# Generated by Django 5.1.1 on 2024-09-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saude', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicomedico',
            name='doencas_preexistentes',
        ),
        migrations.RemoveField(
            model_name='historicomedico',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='historicomedico',
            name='medicamentos_atual',
        ),
        migrations.RemoveField(
            model_name='historicomedico',
            name='nome_paciente',
        ),
        migrations.AddField(
            model_name='historicomedico',
            name='doencas',
            field=models.TextField(blank=True, default='Sem deonças pré-existentes'),
        ),
        migrations.AddField(
            model_name='historicomedico',
            name='familiar',
            field=models.TextField(blank=True, default='Sem doenças familiares'),
        ),
        migrations.AddField(
            model_name='historicomedico',
            name='medicacao',
            field=models.TextField(blank=True, default='Não usa medicamento'),
        ),
        migrations.AddField(
            model_name='historicomedico',
            name='nome',
            field=models.CharField(default='Sem nome', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicomedico',
            name='alergias',
            field=models.TextField(blank=True, default='Sem alergias'),
        ),
        migrations.AlterField(
            model_name='historicomedico',
            name='cirugias',
            field=models.TextField(blank=True, default='Sem cirugias'),
        ),
        migrations.AlterField(
            model_name='historicomedico',
            name='idade',
            field=models.PositiveIntegerField(default='Sem idade'),
        ),
    ]
