# Generated by Django 5.1.1 on 2024-11-11 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0002_locais_doenças'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoencasBairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Locais_doencas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('deonca_bairro', models.ForeignKey(default='valor_padrao', on_delete=django.db.models.deletion.CASCADE, to='saude.doencasbairro')),
            ],
        ),
        migrations.DeleteModel(
            name='Locais_doenças',
        ),
    ]
