# Generated by Django 5.1.1 on 2024-09-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saude', '0002_remove_historicomedico_doencas_preexistentes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicomedico',
            name='familiar',
        ),
        migrations.AlterField(
            model_name='historicomedico',
            name='idade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
