# Generated by Django 5.1.1 on 2024-10-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0003_bairros_locais'),
    ]

    operations = [
        migrations.AddField(
            model_name='locais',
            name='info_adicional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
