# Generated by Django 5.1.1 on 2024-11-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0004_rename_deonca_bairro_locais_doencas_doenca_bairro'),
    ]

    operations = [
        migrations.AddField(
            model_name='locais_doencas',
            name='doenca_locais',
            field=models.CharField(default='Não informado', max_length=255),
        ),
    ]
