# Generated by Django 5.1.1 on 2024-09-30 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saude', '0004_especialidade_local_consulta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SintomasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintomas', models.TextField()),
                ('periodo', models.CharField(default='Desconhecido', max_length=100)),
                ('dor', models.IntegerField(default=0)),
                ('quando_dor', models.CharField(default='Nunca', max_length=50)),
                ('algo_mais', models.TextField(blank=True, default='N/A')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
