# Generated by Django 5.1.1 on 2024-10-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0004_locais_info_adicional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_adicional', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='locais',
            name='info_adicional',
        ),
    ]
