# Generated by Django 5.1.1 on 2024-11-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0005_locais_doencas_doenca_locais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locais_doencas',
            name='doenca_locais',
        ),
    ]
