# Generated by Django 5.1.1 on 2024-10-22 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0005_info_local_remove_locais_info_adicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_local',
            name='locais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='saude.locais'),
        ),
    ]
