# Generated by Django 5.1.1 on 2024-10-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0006_info_local_locais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info_local',
            old_name='info_adicional',
            new_name='nome',
        ),
    ]
