# Generated by Django 5.1.1 on 2024-09-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sintomasusuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
