# Generated by Django 5.1.1 on 2024-09-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0003_alter_sintomasusuario_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sintomasusuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
