# Generated by Django 5.1.1 on 2024-09-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0004_alter_sintomasusuario_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sintomasusuario',
            name='algo_mais',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AddField(
            model_name='sintomasusuario',
            name='dor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sintomasusuario',
            name='periodo',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
        migrations.AddField(
            model_name='sintomasusuario',
            name='quando_dor',
            field=models.CharField(default='Nunca', max_length=50),
        ),
    ]
